apiVersion: v1
kind: Service
metadata:
  name: node-todo-app
spec:
  type: LoadBalancer
  selector:
    app: node-todo-app
  ports:
    - protocol: TCP
      port: 80          # Port exposed by the LoadBalancer
      targetPort: 8000  # Port on which the application is running in the container
